"use client";

import { useState } from "react";
import { type Agent, type Turn, type TurnDetail } from "@/lib/api";
import { useT } from "@/lib/i18n/LocaleProvider";
import { activityLabel, IconButton, Status, Time, turnTitle } from "./ui";

export function WorkInspector({ turns, detail, agent, focusId, selectedId, busy, onFocus, onInspect, onNewTask, onControl, onClose }: { turns: Turn[]; detail: TurnDetail | null; agent?: Agent; focusId: string | null; selectedId: string | null; busy: boolean; onFocus: (turn: Turn) => void; onInspect: (turn: Turn) => void; onNewTask: () => void; onControl: (action: "cancel" | "resume" | "stop-loop") => void; onClose: () => void }) {
  const t = useT();
  const [tab, setTab] = useState<"activity" | "details">("activity");
  const active = detail?.status === "running" || detail?.status === "waiting_user";
  return <>
    <header className="inspector-header"><h2>{t("work")}</h2><IconButton label={t("collapseWork")} onClick={onClose}>×</IconButton></header>
    <div className="inspector-scroll"><section className="turn-section"><div className="section-label"><span>{t("tasks")} <span className="count">{turns.length}</span></span><button className="text-button" onClick={onNewTask} disabled={busy || !agent}><span aria-hidden="true">＋</span>{t("newTask")}</button></div>{!turns.length ? <p className="quiet-empty">{t("noTurnsText")}</p> : <ul className="turn-list">{turns.map(turn => <li key={turn.turn_id} className={`turn-row ${turn.turn_id === selectedId ? "selected" : ""}`} data-turn-id={turn.turn_id}><button className="turn-select" onClick={() => onFocus(turn)} disabled={busy} title={t("focusTask")}><span className={`turn-glyph status-${turn.status}`} aria-hidden="true">{turn.branch_id === "main" ? "◌" : "⑂"}</span><span><strong>{turnTitle(turn, t)}</strong><span className="turn-row-meta"><Status status={turn.status} /><small>{t(turn.turn_id === focusId ? "focus" : "background")}</small></span></span></button><IconButton label={`${t("inspect")} ${turnTitle(turn, t)}`} onClick={() => onInspect(turn)}>↗</IconButton></li>)}</ul>}</section>
      {detail && <section className="selected-work"><div className="selected-work-title"><span className="section-label">{t("details")}</span><Status status={detail.status} /></div><h3>{turnTitle(detail, t)}</h3><div className="branch-label">⑂ {detail.branch_id === "main" ? t("main") : `${t("branch")} · ${detail.branch_id.slice(-6)}`}</div>{detail.loop && <div className="loop-fact"><span>↻ {t("loopRunning")}</span><strong>{t("loopIteration")} {detail.loop.current_iteration} / {detail.loop.max_iterations ?? "∞"}</strong>{detail.loop.stop_requested && <small>{t("stopRequested")}</small>}</div>}
        <div className="turn-controls">{detail.loop && <button className="button secondary compact" onClick={() => onControl("stop-loop")} disabled={busy || detail.loop.stop_requested}>{t(detail.loop.stop_requested ? "stopRequested" : "stopLoop")}</button>}{active && agent?.supports_cancel && <button className="button danger compact" onClick={() => onControl("cancel")} disabled={busy}>{t("cancelExecution")}</button>}{detail.status === "interrupted" && agent?.supports_resume && <button className="button secondary compact" onClick={() => onControl("resume")} disabled={busy}>{t("resume")}</button>}</div>
        <div className="inspector-tabs" role="tablist" aria-label={t("workPanel")}><button role="tab" aria-selected={tab === "activity"} onClick={() => setTab("activity")}>{t("activity")}</button><button role="tab" aria-selected={tab === "details"} onClick={() => setTab("details")}>{t("details")}</button></div>
        {tab === "activity" ? <div role="tabpanel" className="activity-list">{!detail.events.length ? <p className="quiet-empty">{t("noActivity")}</p> : detail.events.slice().reverse().map(event => <div className="activity-row" key={event.event_id}><span className="activity-dot" /><div><p>{activityLabel(event, t)}</p><Time value={event.created_at} /></div></div>)}</div> : <dl className="fact-list" role="tabpanel"><dt>{t("started")}</dt><dd><Time value={detail.created_at} full /></dd><dt>{t("updated")}</dt><dd><Time value={detail.last_event_at} full /></dd><dt>{t("session")}</dt><dd className="mono">{detail.native_session_ref ?? t("sessionNone")}</dd><dt>{t("turnId")}</dt><dd className="mono">{detail.turn_id}</dd><dt>{t("branchId")}</dt><dd className="mono">{detail.branch_id}</dd></dl>}
      </section>}
      <section className="agent-section"><span className="section-label">{t("agent")}</span><div className="agent-profile"><span className="agent-initial large">{agent?.agent_id === "kanaloa" ? "K" : "·"}</span><div><strong>{agent?.agent_id === "kanaloa" ? "Kanaloa" : agent?.display_name || agent?.agent_id || t("agentUnavailable")}</strong>{agent && <small><span className={`status-dot ${agent.status === "ready" ? "ready" : "idle"}`} />{t(agent.status === "ready" ? "agentReady" : agent.status === "idle" ? "agentIdle" : agent.status === "unavailable" ? "agentUnavailable" : agent.status)}</small>}</div></div>{agent && <details className="capabilities"><summary>{t("capabilities")}</summary><dl className="fact-list"><dt>{t("steer")}</dt><dd>{t(agent.steer_mode)}</dd><dt>{t("branch")}</dt><dd>{t(agent.branch_mode)}</dd><dt>{t("parallel")}</dt><dd>{agent.supports_parallel_sessions ? agent.max_parallel_sessions ?? t("unlimited") : t("unsupported")}</dd>{([['stream', 'supports_stream'], ['resume', 'supports_resume'], ['cancel', 'supports_cancel'], ['approvalCapability', 'supports_approval']] as const).map(([key, capability]) => <div className="capability-pair" key={key}><dt>{t(key)}</dt><dd>{t(agent[capability] ? "supported" : "unsupported")}</dd></div>)}</dl></details>}</section>
    </div>
  </>;
}
